Add OcpSandbox  kind
rhpds/sandbox pull request #55
Opened 2024-03-05 15:08 UTC by agonzalezrh

The provided change is a set of modifications to add the OcpSandbox resource kind to the Sandbox API.

New types:
* `OcpSharedClusterConfiguration`: Shared cluster configuration (with virt or not) that is used by the sandbox API to schedule and create resources for OcpSandboxes.
* `OcpSandbox`: Basically a namespace + service account

**How sandboxes are scheduled**
1. use annotations to filter the cluster in the request.   OcpCluster are created with annotations. When requesting, provide `cloud_selector` to match the annotations of the desired cluster(s). Behind the scene that uses postgresql `@>` operator to filter the OcpClusters. Example of request in agnosticV:
    ```yaml
     __meta__:
       sandboxes:
         - kind: OcpSandbox
           cloud_selector:
             virt: enable
             region: na
    ```
2. look at resources (CPU/Memory) on the clusters before electing
3. If cluster has room, then create the resources (namespace, serviceaccount)

**Go Source Code Changes:**

In `account_handlers.go`, significant changes include the introduction of handling OpenShift (OCP) accounts along with AWS accounts. This includes creating a new handler for OCP accounts, adjusting existing functions to manage accounts by their kind (e.g., AWS or OCP), and logging enhancements.

Adjustments in error handling, HTTP status codes, and addition of comments for clarity.
In `handlers.go`, the creation of placements now supports OCP resources, error handling improvements, and changes to ensure resources are correctly cleaned up in case of errors during placement creation.

**Enhanced Annotations Handling:**

The handling of annotations within placement requests has been refined. This includes the implementation of a Merge function for annotations, allowing for the combination of annotations from different sources. This change ensures that annotations provided at different levels (e.g., placement request level vs. individual resource request level) are properly consolidated, enhancing flexibility and the ability to pass and utilize metadata throughout the system.

The AWS account management logic within internal/dynamodb/accounts.go has been updated to support annotations. This includes the ability to store and retrieve annotations associated with AWS accounts, allowing for richer metadata management associated with AWS resources. This enhancement supports more nuanced account management and allocation strategies, catering to specific needs or criteria defined via annotations.

For example, with this change,  in agnosticv it'll now be possible to do: 
```yaml
__meta__:
  sandboxes:
    - kind: OcpSandbox
      var: ocp_account
      annotations:
        purpose: webapp
    - kind: AwsSandbox
      var: aws_account
      annotations:
        purpose: storage
    - kind: AwsSandbox
      var: aws_account2
      annotations:
        purpose: automation
```
And in Anarchy use the annotations to request the different accounts and pass that information so the accounts can be identified when retrieving them

```json
{
  "service_uuid": "{{uuid}}",
  "resources": [
    {"kind": "OcpSandbox", "annotations":{"var":"ocp_account", "purpose": "webapp"}},
    {"kind": "AwsSandbox", "annotations":{"var":"aws_account", "purpose": "storage"}},
    {"kind": "AwsSandbox", "annotations":{"var":"aws_account2", "purpose": "automation"}},
  ],
  "annotations": {
    "guid": "...",
    "owner": "...",
  }
}
```
That is done in PR https://github.com/rhpds/babylon_anarchy_governor/pull/83

**SQL Migration Scripts:**

The addition of `005_ocp_sandbox.up.sql` and `005_ocp_sandbox.down.sql` for managing OpenShift providers in the database. This includes creating a new table ocp_providers and updating the resources table to accommodate OCP-specific data.

**Swagger API Documentation (swagger.yaml):**

Updated the API documentation to reflect new endpoints and parameters related to the handling of different kinds of sandbox accounts, specifically the inclusion of OCP alongside AWS.

**Dependency and Module Changes (go.mod, go.sum):**

Updated various dependencies, including the Kubernetes client libraries (k8s.io/*) to newer versions. These updates support the handling of OCP resources.
General updates to dependencies and removal of unused ones.

Overall, these changes aim to expand the project's capabilities by introducing support for OpenShift accounts alongside AWS accounts, improving error handling and logging, and updating dependencies to support new features and ensure compatibility.

**Makefile Changes:** Introduced a new section in the migrate target to print the database URL without exposing the password, and ask for confirmation before proceeding.

2024-03-06 12:07 UTC, fridim requested changes
Thank you!
Here is my review.

Make sure you include functional tests

You can use python or HURL files like done here: https://github.com/rhpds/sandbox/tree/main/tests

2024-03-06 12:07 UTC, fridim commented on cmd/sandbox-api/handlers.go
> +			}
This should be part of `DeletePlacementByServiceUuid  function i think

so part of placement.Delete(..)    so you need to pass the ocp Account Provider down to it and deal with the deletion there.

The handler should stay simple in this case

2024-03-06 12:07 UTC, fridim commented on db/migrations/005_ocp_providers.down.sql
> +DROP TRIGGER IF EXISTS Ocp_providers_updated_at ON Ocp_providers;
capital 0 ?

2024-03-06 12:07 UTC, fridim commented on deploy/helm-api/values.yaml
> +  image: quay.io/agonzalezrh/sandbox-api
change back before merging

2024-03-06 12:07 UTC, fridim commented on deploy/helm-api/values.yaml
> +dynamodb_region: us-east-2
change back before merge

2024-03-06 12:13 UTC, fridim commented on cmd/sandbox-api/handlers.go
> +      placementRequest.Annotations["OCPProvider"] = account.OCPProvider
I would save the credentials in DB table `resources` when created, with the appropriate resource type.
You'll have to add a column for the data  and make sure credential is encrypted using the vaultsecret

2024-03-06 12:15 UTC, fridim commented
you also need to patch `func (h *BaseHandler) GetPlacementHandler(w http.ResponseWriter, r *http.Request) {`  to return the OCP creds
That will be needed for stop/start/status actions

2024-04-05 08:48 UTC, bbethell-1 approved these changes

2024-04-05 09:04 UTC, fridim approved these changes

2024-04-05 14:33 UTC, jkupferer commented on tests/002_ocp.hurl
> +# Get all OcpAccounts using service_uuid query
This is getting all OcpSandboxes, right, not OCpAccounts?

2024-04-05 14:33 UTC, jkupferer commented on tests/002_ocp.hurl
> +# Get all OcpAccounts
This is getting all OcpSandboxes, right, not OCpAccounts?

2024-04-05 14:35 UTC, jkupferer commented on tests/002_ocp.hurl
> +# Get  OcpAccount using name
OcpAccount or OcpSandbox?

2024-04-05 14:58 UTC, fridim commented on tests/002_ocp.hurl
> +# Get  OcpAccount using name
I wanted to rename all OcpAccount occurences with OcpSandbox to address that confusion. I think i'll do it as part of this PR

2024-04-05 15:35 UTC, jkupferer commented on internal/models/ocp_account.go
> +		serviceAccountName = serviceAccountName[:min(63, len(serviceAccountName))] // truncate to 63
No need for the service account name to have the guid + uuid suffix. ServiceAccounts are already scoped to the namespace, so probably simpler to just have the service account named `sandbox`?

2024-04-05 15:41 UTC, jkupferer commented on internal/models/ocp_account.go
> +		}
This bit about create `kubevirt.io:admin` is unnecessary because if this cluster role exists then it already gets rolled into the `admin` role.
https://docs.openshift.com/container-platform/4.15/virt/about_virt/virt-security-policies.html#default-cluster-roles-for-virt_virt-security-policies

2024-04-05 15:44 UTC, jkupferer commented on internal/models/ocp_account.go
> +		}
Is this a custom cluster role? If so, should be defined to be included into admin like kubevirt.io:admin?

2024-04-05 15:48 UTC, jkupferer commented on internal/models/ocp_account.go
> +	serviceAccountName = serviceAccountName[:min(63, len(serviceAccountName))] // truncate to 63
Better to just use `sandbox` as the `serviceAccountName`

2024-04-05 15:48 UTC, jkupferer commented on internal/models/ocp_account.go
> +         r.id,
weird indent?

2024-04-05 15:48 UTC, jkupferer commented on internal/models/ocp_account.go
> +         r.id,
another weird indent?

2024-04-05 15:49 UTC, jkupferer commented on internal/models/ocp_account.go
> +         r.id,
here too?

2024-04-05 16:11 UTC, fridim commented on internal/models/ocp_account.go
> +		}
commenting that part for now

2024-04-05 18:18 UTC, jkupferer approved these changes

2024-04-05 18:20 UTC, merged